name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Clonagem do projeto para a máquina virtual do github
    - name: Clonagem do Projeto
      uses: actions/checkout@v2
      
    # Passo 2: Configuração do Python
    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.  # Especifique a versão do Python que você usa
      
    # Passo 3: Instalação das dependencias do projeto
    - name: Instalação das dependencias do Projeto
      run: |
        python -m pip install --upgrade pip   
        pip install robotframework   
      
    # Passo 3: Rodar os testes automatizados com Robot Framework
      - name: Run Robot Framework Tests
        run: robot --outputdir results tests/
 
    # Passo 4: Upload dos resultados dos testes para visualização
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()      # caso o teste falhe, será salvo o resultado
      with:
        name: resultado-testes
        path: ./logs